// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages_robocup_ssl_radio.proto

#ifndef PROTOBUF_messages_5frobocup_5fssl_5fradio_2eproto__INCLUDED
#define PROTOBUF_messages_5frobocup_5fssl_5fradio_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "messages_robocup_ssl_cmd.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_messages_5frobocup_5fssl_5fradio_2eproto();
void protobuf_AssignDesc_messages_5frobocup_5fssl_5fradio_2eproto();
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fradio_2eproto();

class SSL_RadioPacket;

// ===================================================================

class SSL_RadioPacket : public ::google::protobuf::Message {
 public:
  SSL_RadioPacket();
  virtual ~SSL_RadioPacket();
  
  SSL_RadioPacket(const SSL_RadioPacket& from);
  
  inline SSL_RadioPacket& operator=(const SSL_RadioPacket& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SSL_RadioPacket& default_instance();
  
  void Swap(SSL_RadioPacket* other);
  
  // implements Message ----------------------------------------------
  
  SSL_RadioPacket* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SSL_RadioPacket& from);
  void MergeFrom(const SSL_RadioPacket& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .SSL_RadioFrame RadioFrame = 1;
  inline bool has_radioframe() const;
  inline void clear_radioframe();
  static const int kRadioFrameFieldNumber = 1;
  inline const ::SSL_RadioFrame& radioframe() const;
  inline ::SSL_RadioFrame* mutable_radioframe();
  inline ::SSL_RadioFrame* release_radioframe();
  
  // @@protoc_insertion_point(class_scope:SSL_RadioPacket)
 private:
  inline void set_has_radioframe();
  inline void clear_has_radioframe();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::SSL_RadioFrame* radioframe_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_messages_5frobocup_5fssl_5fradio_2eproto();
  friend void protobuf_AssignDesc_messages_5frobocup_5fssl_5fradio_2eproto();
  friend void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fradio_2eproto();
  
  void InitAsDefaultInstance();
  static SSL_RadioPacket* default_instance_;
};
// ===================================================================


// ===================================================================

// SSL_RadioPacket

// optional .SSL_RadioFrame RadioFrame = 1;
inline bool SSL_RadioPacket::has_radioframe() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SSL_RadioPacket::set_has_radioframe() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SSL_RadioPacket::clear_has_radioframe() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SSL_RadioPacket::clear_radioframe() {
  if (radioframe_ != NULL) radioframe_->::SSL_RadioFrame::Clear();
  clear_has_radioframe();
}
inline const ::SSL_RadioFrame& SSL_RadioPacket::radioframe() const {
  return radioframe_ != NULL ? *radioframe_ : *default_instance_->radioframe_;
}
inline ::SSL_RadioFrame* SSL_RadioPacket::mutable_radioframe() {
  set_has_radioframe();
  if (radioframe_ == NULL) radioframe_ = new ::SSL_RadioFrame;
  return radioframe_;
}
inline ::SSL_RadioFrame* SSL_RadioPacket::release_radioframe() {
  clear_has_radioframe();
  ::SSL_RadioFrame* temp = radioframe_;
  radioframe_ = NULL;
  return temp;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_messages_5frobocup_5fssl_5fradio_2eproto__INCLUDED
